flowchart LR
  A[Understand Existing<br/>Code Repository] --> B[Dev Design Doc]
  B --> C[Define Functional<br/>Boundaries]
  B --> D[Define Technical<br/>Solution]
  B --> E[Define Interface<br/>Contract]
